name: Fetch Trending of Github Daily

permissions:
  contents: write

on:
  schedule:
    - cron: '1 0 * * *' # 每天 UTC 0 点运行
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT

      - name: Fetch trending from github
        run: |
          mkdir -p daily weekly monthly
          curl -s "https://githubtrending.lessx.xyz/trending?since=daily" \
            -o "daily/${{ steps.get-timestamp.outputs.timestamp }}.json"
          echo "Fetched and saved to daily/${{ steps.get-timestamp.outputs.timestamp }}.json"

          curl -s "https://githubtrending.lessx.xyz/trending?since=weekly" \
            -o "weekly/${{ steps.get-timestamp.outputs.timestamp }}.json"
          echo "Fetched and saved to weekly/${{ steps.get-timestamp.outputs.timestamp }}.json"

          curl -s "https://githubtrending.lessx.xyz/trending?since=monthly" \
            -o "monthly/${{ steps.get-timestamp.outputs.timestamp }}.json"
          echo "Fetched and saved to monthly/${{ steps.get-timestamp.outputs.timestamp }}.json"

      - name: Commit and push new trending files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily/*.json weekly/*.json monthly/*.json
          git commit -m "Add trending for ${{ steps.get-timestamp.outputs.timestamp }} UTC" || echo "Nothing to commit"
          git push
